# 7. 재시작 정책 테스트
#    - OnFailure : 컨테이너가 실패하면 재시작하는 정책.
#    - 컨테이너가 실패가 되도록 제어가 가능한 busybox container 를 사용한다.
#    - command : ["sh", "-c", "sleep 5"]
#      busybox 컨테이너가 실행이 되면,
#      쉘에서 3초간 sleep 하고, 5초가 지나면, 컨테이너는 정상 종료된다.
#      => 5초가 되기전에는 status가 runnig 이고
#         5초가 지난후에는 status가 Completed( 정상종료 ) 가 된다

#      kubectl apply -f ex1-3.yaml
#      kubectl get pod
#      kubectl delete pod my-simple-pod
#      kubectl describe pod my-simple-pod
#    - pod 와 container 의 상태를 확인 할 수 있다.
#      pod : Succeeded
#      container : Terminated( Completed )
#                  Exit code : 0 ( 정상 종료 )
#                  Restart Count : 0
#    - 여기 중요한 것은 pod의 상태이고, Status가 Succeeded 임으로
#      더 이상 재시작하지 않을 것이라는 것을 알 수 있다.
apiVersion: v1
kind: Pod
metadata:
  name: my-simple-pod
spec:
  restartPolicy: OnFailure # 재시작 정책 : 실패하면 재실행.
  containers:
    - name: my-container
      #image: nginx:1.24
      image: busybox
      # command ; busybox container가 실행이 될 때 실행할 명령어.
      command: ["sh", "-c", "sleep 5"]

