# configMap 실습 예제
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
  # 관리할 환경변수를 설정. key, value 형태로 설정
data:
  profile: "dev"
  db_host: "10.20.30.40"
  welcom-script: | # multi-line 작성을 위해 | 를 사용한다
    echo Hello!
    echo DB is $db_host


# kubectl apply -f ex6-configmap.yaml

# kubectl get configmap

# kubectl describe configmap my-confi