spring:
  datasource:
    url: jdbc:mysql://mysql-service:3306/test  # MySQL 서비스 주소 및 데이터베이스 이름
    username: root  # MySQL 사용자 이름
    password: 1234  # MySQL 비밀번호
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect  # MySQL에 맞는 Dialect 설정
    hibernate:
      ddl-auto: create  # 데이터베이스 스키마 자동 업데이트 설정 (필요에 따라 create 또는 validate로 변경 가능)
    show-sql: true  # SQL 쿼리 로그 출력
    properties:
      hibernate:
        format_sql: true  # 포맷된 SQL 출력